### ISSUE TITLE
After updating matrix-synapse to version 1.27.0, the matrix-synapse does not see the module

### ISSUE THREAD

**Issue by tmasky** [t2bot/synapse-simple-antispam#1]
After updating matrix-synapse to version 1.27.0, the matrix-synapse does not see the module

matrix-synapse: Traceback (most recent call last):         
matrix-synapse:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
matrix-synapse:     return _run_code(code, main_globals, None,              
matrix-synapse:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
matrix-synapse:     exec(code, run_globals)
matrix-synapse:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py", line 507, in <module>                                                               
matrix-synapse:     main()                                                                 
matrix-synapse:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py", line 502, in main                                                                   
matrix-synapse:     hs = setup(sys.argv[1:])                                 
matrix-synapse:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py", line 332, in setup
matrix-synapse:     config = HomeServerConfig.load_or_generate_config(                                                                                                                                           
matrix-synapse:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/_base.py", line 711, in load_or_generate_config                                        
matrix-synapse:     obj.parse_config_dict(                                                                                                                                                                       
matrix-synapse:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/_base.py", line 730, in parse_config_dict               
matrix-synapse:     self.invoke_all(                                                                                                                                                                             
matrix-synapse:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/_base.py", line 359, in invoke_all                                                    
matrix-synapse:     res[name] = getattr(config, func_name)(*args, **kwargs)                                                                                                                                      
matrix-synapse:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/spam_checker.py", line 36, in read_config
matrix-synapse:     self.spam_checkers.append(load_module(spam_checkers, ("spam_checker",)))                                                         
matrix-synapse:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/util/module_loader.py", line 49, in load_module                
matrix-synapse:     module = importlib.import_module(module)                                                                                                                                                     
matrix-synapse:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                        
matrix-synapse:     return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                  
matrix-synapse:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
matrix-synapse:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
matrix-synapse:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
matrix-synapse: ModuleNotFoundError: No module named 'synapse_simple_antispam'

**Comment by tmasky** [comment]
My homeserver.yaml:
spam_checker:
  module: "synapse_simple_antispam.AntiSpamInvites"
  config:
    # A list of homeservers to block invites from.
    locked_homeservers:
      - calamari.space

**Comment by turt2live** [comment]
fixed
